apiVersion: apps/v1
kind: Deployment
metadata:
  name: webber-web
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: webber-web
  template:
    metadata:
      labels:
        app: webber-web
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: webber-web
          image: registry.digitalocean.com/tppt-registry/webber-web:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /henge/
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /henge
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 2
