apiVersion: apps/v1
kind: Deployment
metadata:
  name: webber-web
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: webber-web
  template:
    metadata:
      labels:
        app: webber-web
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: webber-web
          image: registry.digitalocean.com/tppt-registry/webber-web:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/config.json
              subPath: config.json
      volumes:
        - name: config-volume
          configMap:
            name: webber-web-config
            items:
              - key: config.json
                path: config.json